name: mdreader
description: A privacy-first offline Markdown reader
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_markdown: ^0.6.18
  file_picker: ^6.1.1
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  google_fonts: ^6.1.0
  flutter_highlight: ^0.7.0
  markdown: ^7.1.1
  path_provider: ^2.1.1
  uuid: ^4.0.0
  flutter_colorpicker: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/

flutter_intl:
  enabled: true